# Generated by Django 3.0.6 on 2020-05-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=60, verbose_name='Товар')),
                ('text', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=17, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить в списке?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
        ),
    ]
